// MISSING PIECES ACTIONS TYPE NAMES
export const SET_DATA_SOURCE = "SET_DATA_SOURCE";
export const SET_SELECTED_ROW_DETAILS_ID = "SET_SELECTED_ROW_DETAILS_ID";
export const SET_MODAL_OPEN = "SET_MODAL_OPEN";
export const SET_PAGE = "SET_PAGE";
export const SET_SEARCH = "SET_SEARCH";

// EDARA EXPENSES ACTIONS TYPE NAMES
export const SET_SELECTED_ROW_DETAILS = "SET_SELECTED_ROW_DETAILS";
export const SET_ENTRY_MODAL_OPEN = "SET_ENTRY_MODAL_OPEN";
export const SET_INVOICE_MODAL_OPEN = "SET_INVOICE_MODAL_OPEN";
